/** Tabel label manusiawi: nama tool → teks yang ditampilkan pengguna. */
export const HUMAN_TOOL_LABELS: [RegExp, string][] = [
  // Workspace & files
  [/general:list_attachments/, "Melihat daftar lampiran"],
  [/general:read_attachment/, "Membaca lampiran"],
  [/general:list_files/, "Melihat file workspace"],
  [/general:read_file/, "Membaca file"],
  [/general:write_file/, "Menyimpan perubahan file"],
  [/general:search_code/, "Mencari kode"],
  [/general:search_files/, "Mencari file"],
  [/general:replace_text/, "Mengganti teks"],
  [/general:apply_patch/, "Menerapkan perubahan kode"],
  [/general:extract_zip/, "Mengekstrak arsip"],
  [/general:import_attachment/, "Menyalin lampiran ke workspace"],
  [/archive:create/, "Membuat arsip ZIP"],
  // Shell, project, proses
  [/general:execute_shell/, "Menjalankan command"],
  [/project:detect/, "Mendeteksi project"],
  [/project:scripts/, "Melihat scripts project"],
  [/project:run_script/, "Menjalankan script project"],
  [/general:start_process/, "Memulai proses"],
  [/general:process_output/, "Membaca output proses"],
  [/general:process_status/, "Memeriksa status proses"],
  [/general:stop_process/, "Menghentikan proses"],
  // Git
  [/git:status/, "Memeriksa status Git"],
  [/git:diff/, "Melihat perubahan Git"],
  [/git:log/, "Melihat riwayat commit"],
  [/git:show/, "Melihat detail commit"],
  [/git:branches/, "Melihat branch"],
  [/git:changed_files/, "Melihat file yang berubah"],
  [/git:compare/, "Membandingkan versi kode"],
  [/git:add/, "Menyiapkan perubahan Git"],
  [/git:commit/, "Menyimpan commit"],
  [/git:create_branch/, "Membuat branch"],
  [/git:checkout/, "Berpindah branch/versi"],
  [/git:restore/, "Membatalkan perubahan lokal"],
  // Web, data, compute, sistem
  [/web:search/, "Mencari informasi di web"],
  [/web:fetch_url/, "Membuka halaman web"],
  [/data:parse_json|data:validate_json/, "Memeriksa data JSON"],
  [/data:format_json/, "Merapikan JSON"],
  [/data:query_json/, "Mengambil bagian data JSON"],
  [/data:inspect_csv/, "Memeriksa data CSV"],
  [/data:query_csv/, "Membaca data CSV"],
  [/data:statistics/, "Menghitung statistik data"],
  [/text:diff/, "Membandingkan teks"],
  [/text:count/, "Menghitung teks"],
  [/text:search/, "Mencari dalam teks"],
  [/compute:execute_python/, "Menghitung dengan Python"],
  [/system:platform/, "Membaca platform sistem"],
  [/system:resources/, "Membaca resource sistem"],
  [/system:network_interfaces/, "Membaca interface jaringan host"],
  [/system:environment_capabilities/, "Memeriksa kapabilitas environment"],
  // Integrasi
  [/calendar:list_events/, "Melihat jadwal kalender"],
  [/calendar:create_event/, "Membuat acara kalender"],
  [/calendar:delete_event/, "Menghapus acara kalender"],
  [/mikrotik:list_routers/, "Mencari router tersimpan"],
  [/mikrotik:connect_router/, "Menghubungkan router"],
  [/drive:search_files/, "Mencari file Google Drive"],
  [/drive:get_file|drive:read_document/, "Membaca dokumen Drive"],
  [/drive:create_text_file/, "Membuat file di Drive"],
  [/gmail:search_messages/, "Mencari email"],
  [/gmail:read_message/, "Membaca email"],
  [/gmail:create_draft/, "Menyiapkan draft email"],
  [/gmail:send_message/, "Mengirim email"],
  [/telegram:get_bot|telegram:get_chat/, "Memeriksa Telegram"],
  [/telegram:send_message/, "Mengirim pesan Telegram"],
  [/check_connection/i, "Memeriksa status koneksi"],
  [/remove_vlan_interface|delete_vlan/i, "Menghapus interface VLAN"],
  [/create_vlan_interface/i, "Membuat interface VLAN"],
  [/list_vlan_interfaces/i, "Membaca interface VLAN"],
  [/remove_bridge|delete_bridge/i, "Menghapus interface Bridge"],
  [/create_bridge/i, "Membuat interface Bridge"],
  [/list_bridges|print_bridge/i, "Membaca interface Bridge"],
  [/add_bridge_vlan/i, "Mengonfigurasi VLAN Bridge"],
  [/add_bridge_port/i, "Menghubungkan port ke Bridge"],
  [/remove_ip_pool|delete_ip_pool/i, "Menghapus IP Pool"],
  [/create_ip_pool/i, "Membuat IP Pool"],
  [/list_ip_pools/i, "Membaca IP Pool"],
  [/remove_ip_address|delete_ip/i, "Menghapus IP address"],
  [/add_ip_address/i, "Menambahkan IP address"],
  [/list_ip_addresses|print_ip_address/i, "Membaca IP address"],
  [/list_interfaces/i, "Membaca interface"],
  [/list_routes|print_ip_route/i, "Membaca route"],
  [/add_dhcp_server/i, "Menambahkan DHCP Server"],
  [/add_dhcp_network/i, "Menambahkan DHCP Network"],
  [/dhcp_client|get_dhcp_clients/i, "Membaca DHCP client"],
  [/dhcp_server/i, "Membaca DHCP server"],
  [/add_nat_rule/i, "Menambahkan aturan NAT"],
  [/firewall_nat|list_firewall_nat/i, "Membaca NAT"],
  [/add_filter_rule|add_firewall_rule/i, "Menambahkan aturan firewall"],
  [/firewall.*filter|list_firewall_rules/i, "Membaca firewall filter"],
  [/design_network_segment/i, "Mendesain segmen jaringan"],
  [/system_resource|resource/i, "Membaca resource sistem"],
  [/identity/i, "Memeriksa koneksi & identitas"],
  [/find_tools|routeros_search/i, "Mencari tool yang sesuai"],
];
